    version: 2.1
    executors:
      docker-publisher:
        environment:
          IMAGE_NAME: hadyelzayady/instabug-task
        docker:
          - image: circleci/buildpack-deps:stretch
    jobs:
      build:
        working_directory: ~/djangoforbeginners/ch14-permissions-and-authorizations
        executor: docker-publisher
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Docker image
              command: |
                docker build -t $IMAGE_NAME:latest .
          - run:
              name: Archive Docker image
              command: docker save -o image.tar $IMAGE_NAME
          - persist_to_workspace:
              root: .
              paths:
                - ./image.tar
      test:
        working_directory: ~/djangoforbeginners/ch14-permissions-and-authorizations
        docker:
          - image: circleci/python:3.6.4
            environment:
              PIPENV_VENV_IN_PROJECT: true
              IMAGE_NAME: hadyelzayady/instabug-task
        steps:
          - checkout
          - run: sudo chown -R circleci:circleci /usr/local/bin
          - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
          - run:
              name: testing
              command: |
                cd ch14-permissions-and-authorizations
                sudo pip install pipenv
                pipenv install
                pipenv run "python manage.py test"

      publish-latest:
        executor: docker-publisher
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - setup_remote_docker
          - run:
              name: Load archived Docker image
              command: docker load -i /tmp/workspace/image.tar
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "23111996Hdesire" | docker login -u "hadyelzayady" --password-stdin
                docker push $IMAGE_NAME:latest
    workflows:
      version: 2
      build-master:
        jobs:
          - test:
              filters:
                branches:
                  only: master
          - build:
              requires:
                - test
              filters:
                branches:
                  only: master
          - publish-latest:
              requires:
                - build
              filters:
                branches:
                  only: master