version: 2
jobs:
  build:
    working_directory: ~/djangoforbeginners/ch14-permissions-and-authorizations
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            cd ch14-permissions-and-authorizations
            sudo pip install pipenv
            pipenv install
            pipenv run "python manage.py test"
      - run:
          command: docker build -t $IMAGE_NAME:latest .
  publish-latest:
        environment:
          IMAGE_NAME: hadyelzayady/instabug-task 
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - setup_remote_docker
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "23111996Hdesire" | docker login -u "hadyelzayady" --password-stdin
                docker push $IMAGE_NAME:latest
              

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish-latest:
          requires:
            - build
          filters:
           branches:
             only: master
