version: 2
jobs:
  build:
    working_directory: ~/djangoforbeginners/ch2-hello-world-app/
    docker:
      - image: circleci/python:3.6.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - run:
          command: |
            cd ch2-hello-world-app
            sudo pip install pipenv
            pipenv install
      - run:
          command: |
            cd ch2-hello-world-app
            pipenv run "python manage.py test"
      - store_test_results:
          path: ch2-hello-world-app/test-results
      - store_artifacts:
          path: ch2-hello-world-app/test-results
          destination: tr1
